---
layout: yml
---
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "src/assets/img/uploads" # Media files will be stored in the repo under src/assets/img/uploads
public_folder: "/assets/img/uploads" # The src attribute for uploaded media will begin with /assets/img/uploads



# Look into wigets https://www.netlifycms.org/docs/widgets for inserting map cordinates
collections:
  - name: "locations" # Used in routes, e.g., /admin/collections/locations
    label: "Location Pages" # Used in the UI
    folder: "src/pages/map" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: html
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "location"}
      - label: "Map Settings"
        name: "map-settings"
        widget: "object"
        fields:
          - {label: "Map Center Cordinates", hint: "must be in format: longitude, latitude e.g. -155.505853, 19.613383", name: "center-coordinates", widget: "string"}
          - {label: "Zoom Level", hint: "minimum zoom is 6, max is 17", name: "zoom-level", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Meta-Title", hint: "Title that shows in browser window/tab ' | Life in the Hawaiian Islands' is automatcally added to the end",name: "meta-title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
