---
layout: yml
---
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "src/assets/img/uploads" # Media files will be stored in the repo under src/assets/img/uploads
public_folder: "/assets/img/uploads" # The src attribute for uploaded media will begin with /assets/img/uploads



# Look into wigets https://www.netlifycms.org/docs/widgets for inserting map cordinates
collections:
  - name: "locations" # Used in routes, e.g., /admin/collections/locations
    label: "Location Pages" # Used in the UI
    folder: "src/pages/map" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: html
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "location"}
      - label: "Map Settings"
        name: "map-settings"
        widget: "object"
        fields:
          - {label: "Map Center Cordinates", hint: "must be in format: longitude, latitude e.g. -156.381, 20.789", name: "center-coordinates", widget: "string"}
          - {label: "Zoom Level", hint: "minimum zoom is 6, max is 17 (default is 11)", name: "zoom-level", widget: "string", default: "11"}
          - {label: "Map Cordinates", hint: "testing map feature", name: "map-cord", widget: "map"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Meta-Title", hint: "Title that shows in browser window/tab ' | Life in the Hawaiian Islands' is automatcally added to the end", name: "meta-title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Location Overview Paragraph", name: "location-overview-paragraph", widget: "text"}
      - label: "Body Content"
        name: "body-content"
        widget: "list"
        types:
          - label: "Paragraph + Buyable Image"
            name: "main-contents"
            widget: "object"
            fields:
              - { label: "Paragraph", name: "content-paragraph", widget: "text" }
              - { label: "Image", name: "buy-image", widget: "image" }
              - { label: "Image Caption", name: "img-caption", widget: "text" }
              - { label: "Shopify ID", name: "shop-id", widget: "string" }
              - { label: "Image-Label", hint: "Must be unique to other images on this page", name: "img-label", widget: "string" }
              
              